name: CLI Continuous Integration (Compilation tests for variations of Actix + Postgres)
on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    paths: 
      - "**.rs"
      - "Cargo.lock"
      - "Cargo.toml"
  pull_request:
    paths: 
      - "**.rs"
      - "Cargo.lock"
      - "Cargo.toml"
env:
  CARGO_TERM_COLOR: always
  
concurrency:
  group:  CI-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # naming convention is: [backend]-[database]-[plugins]
  Actix-Postgres-None:
    name: Actix w/ Postgres and no plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3.2.5
        with:
          path: |
            **/.cargo/.build
            **/target
          key: ${{ runner.os }}-cargo-cli-AP-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: run --bin create-rust-app -- create -c -d postgres -b actix-web test-project
      - run: cd test-project
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build

  Actix-Postgres-All:
    needs: [Actix-Postgres-None]
    name: Actix w/ Postgres and all valid plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3.2.5
        with:
          path: |
            **/.cargo/.build
            **/target
          key: ${{ runner.os }}-cargo-cli-AP-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: run --bin create-rust-app -- create -c -d postgres -b actix-web --plugins=auth,container,graphql,storage,utoipa test-project
      - run: cd test-project
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build

  Actix-Postgres-Container:
    needs: [Actix-Postgres-None]
    name: Actix w/ Postgres and the container plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3.2.5
        with:
          path: |
            **/.cargo/.build
            **/target
          key: ${{ runner.os }}-cargo-cli-AP-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: run --bin create-rust-app -- create -c -d postgres -b actix-web --plugins=container test-project
      - run: cd test-project
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build

  Actix-Postgres-Auth:
    needs: [Actix-Postgres-None]
    name: Actix w/ Postgres and the auth plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3.2.5
        with:
          path: |
            **/.cargo/.build
            **/target
          key: ${{ runner.os }}-cargo-cli-AP-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: run --bin create-rust-app -- create -c -d postgres -b actix-web --plugins=auth test-project
      - run: cd test-project
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build

  Actix-Postgres-Storage:
    needs: [Actix-Postgres-None]
    name: Actix w/ Postgres and the storage plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3.2.5
        with:
          path: |
            **/.cargo/.build
            **/target
          key: ${{ runner.os }}-cargo-cli-AP-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: run --bin create-rust-app -- create -c -d postgres -b actix-web --plugins=storage test-project
      - run: cd test-project
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build

  Actix-Postgres-GraphQL:
    needs: [Actix-Postgres-None]
    name: Actix w/ Postgres and the graphql plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3.2.5
        with:
          path: |
            **/.cargo/.build
            **/target
          key: ${{ runner.os }}-cargo-cli-AP-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: run --bin create-rust-app -- create -c -d postgres -b actix-web --plugins=graphql test-project
      - run: cd test-project
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build

  Actix-Postgres-Utoipa:
    needs: [Actix-Postgres-None]
    name: Actix w/ Postgres and the utoipa plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v3.2.5
        with:
          path: |
            **/.cargo/.build
            **/target
          key: ${{ runner.os }}-cargo-cli-AP-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: run --bin create-rust-app -- create -c -d postgres -b actix-web --plugins=auth,utoipa test-project
      - run: cd test-project
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build